name: Docker Image CI

on:
  push:
    branches: [ main, develop ]
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Tag Version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: DockerHub Login
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v1.2.0
      with:
        platforms: arm,arm64,amd64
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.6.0
    - name: Build & Push Docker image (Latest)
      if:   github.event_name == 'push' && startsWith(github.ref, 'refs/heads/')
      run: docker buildx build . --file Dockerfile -t kcapp/api:latest --platform=linux/arm,linux/arm64,linux/amd64 --push
    - name: Build & Push Docker image (Release version)
      if:   github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      run: docker buildx build . --file Dockerfile -t kcapp/api:${{ env.RELEASE_VERSION }} --platform=linux/arm,linux/arm64,linux/amd64 --push
